from src.lib.data_handling import (
    standardize,
    normalize,
)
from src.single_characteristics.extract_characteristics import (
    word_count_any_parallel,
    word_count_any_in_main_parallel,
    code_length,
    code_length_in_main,
    comments_ratio,
)

characteristics = [
    (word_count_any_parallel("define"), "wc_define"),
    (word_count_any_parallel("using"), "wc_using"),
    (word_count_any_parallel("define int long long"), "wc_define_int_long_long"),
    (word_count_any_parallel("for"), "wc_for"),
    (word_count_any_parallel("if"), "wc_if"),
    (word_count_any_parallel("vector"), "wc_vector"),
    (word_count_any_parallel("rep"), "wc_rep"),
    (word_count_any_parallel("auto"), "wc_auto"),
    (word_count_any_in_main_parallel("for"), "wc(main)_for"),
    (word_count_any_in_main_parallel("if"), "wc(main)_if"),
    (word_count_any_in_main_parallel("vector"), "wc(main)_vector"),
    (word_count_any_in_main_parallel("rep"), "wc(main)_rep"),
    (word_count_any_in_main_parallel("auto"), "wc(main)_auto"),
    (word_count_any_parallel("lower_bound"), "wc_lower_bound"),
    (word_count_any_in_main_parallel("lower_bound"), "wc(main)_lower_bound"),
    (word_count_any_parallel("upper_bound"), "wc_upper_bound"),
    (word_count_any_in_main_parallel("upper_bound"), "wc(main)_upper_bound"),
    (word_count_any_parallel("gcd"), "wc_gcd"),
    (word_count_any_in_main_parallel("gcd"), "wc(main)_gcd"),
    (word_count_any_parallel("lcm"), "wc_lcm"),
    (word_count_any_in_main_parallel("lcm"), "wc(main)_lcm"),
    (word_count_any_parallel("builtin"), "wc_builtin"),
    (word_count_any_in_main_parallel("builtin"), "wc(main)_builtin"),
    (word_count_any_parallel("popcount"), "wc_popcount"),
    (word_count_any_in_main_parallel("popcount"), "wc(main)_popcount"),
    (word_count_any_parallel("template"), "wc_template"),
    (word_count_any_parallel("any_of"), "wc_any_of"),
    (word_count_any_in_main_parallel("any_of"), "wc(main)_any_of"),
    (word_count_any_parallel("all_of"), "wc_all_of"),
    (word_count_any_in_main_parallel("all_of"), "wc(main)_all_of"),
    (word_count_any_parallel("unique"), "wc_unique"),
    (word_count_any_in_main_parallel("unique"), "wc(main)_unique"),
    (word_count_any_parallel("sort"), "wc_sort"),
    (word_count_any_in_main_parallel("sort"), "wc(main)_sort"),
    (word_count_any_parallel("rbegin"), "wc_rbegin"),
    (word_count_any_in_main_parallel("rbegin"), "wc(main)_rbegin"),
    (word_count_any_parallel("ostream"), "wc_ostream"),
    (word_count_any_in_main_parallel("ostream"), "wc(main)_ostream"),
    (word_count_any_parallel("unlocked"), "wc_unlocked"),
    (word_count_any_in_main_parallel("unlocked"), "wc(main)_unlocked"),
    (word_count_any_parallel("constexpr"), "wc_constexpr"),
    (word_count_any_in_main_parallel("constexpr"), "wc(main)_constexpr"),
    (word_count_any_parallel("const"), "wc_const"),
    (word_count_any_in_main_parallel("const"), "wc(main)_const"),
    (word_count_any_parallel("int"), "wc_int"),
    (word_count_any_in_main_parallel("int"), "wc(main)_int"),
    (word_count_any_parallel("long"), "wc_long"),
    (word_count_any_in_main_parallel("long"), "wc(main)_long"),
    (word_count_any_parallel("mint"), "wc_mint"),
    (word_count_any_in_main_parallel("mint"), "wc(main)_mint"),
    (word_count_any_parallel("chmin"), "wc_chmin"),
    (word_count_any_in_main_parallel("chmin"), "wc(main)_chmin"),
    (word_count_any_parallel(";"), "wc_;"),
    (word_count_any_in_main_parallel(";"), "wc(main)_;"),
    (word_count_any_parallel("and"), "wc_and"),
    (word_count_any_in_main_parallel("and"), "wc(main)_and"),
    (word_count_any_parallel("&&"), "wc_&&"),
    (word_count_any_in_main_parallel("&&"), "wc(main)_&&"),
    (word_count_any_parallel("(true)"), "wc_(true)"),
    (word_count_any_in_main_parallel("(true)"), "wc(main)_(true)"),
    (word_count_any_parallel("(1)"), "wc_(1)"),
    (word_count_any_in_main_parallel("(1)"), "wc(main)_(1)"),
    (word_count_any_parallel("(;;)"), "wc_(;;)"),
    (word_count_any_in_main_parallel("(;;)"), "wc(main)_(;;)"),
    (word_count_any_parallel("endl"), "wc_endl"),
    (word_count_any_in_main_parallel("endl"), "wc(main)_endl"),
    (word_count_any_parallel("ii"), "wc_ii"),
    (word_count_any_in_main_parallel("ii"), "wc(main)_ii"),
    (word_count_any_parallel("_"), "wc__"),
    (word_count_any_in_main_parallel("_"), "wc(main)__"),
    (word_count_any_parallel("swap"), "wc_swap"),
    (word_count_any_in_main_parallel("swap"), "wc(main)_swap"),
    (word_count_any_parallel("move"), "wc_move"),
    (word_count_any_in_main_parallel("move"), "wc(main)_move"),
    (word_count_any_parallel("assert"), "wc_assert"),
    (word_count_any_in_main_parallel("assert"), "wc(main)_assert"),
    (code_length, "code_length"),
    (code_length_in_main, "code_length_in_main"),
    (comments_ratio, "comments_ratio"),
]

data_handle_funcs_and_names = [
    (standardize, "standardize"),
    (normalize, "normalize"),
    (lambda x: x, "nothing"),
]
